name: Challenge1

on: 
  push:

jobs:
  job1:
    name: Job 1
    runs-on: ubuntu-latest
    steps:
      - name: Print date
        run: date
      
      - name: Print working directory
        run: pwd
      
      - name: Print current version of directory
        run: ls -la

  job2:
    name: Job 2
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Check version of Python
        run: python --version

      - name: Setup Pandas
        run: pip install pandas

      - name: Create Artifact
        run: |
          echo "# This is my python artifact" > artifact.py
          python artifact.py