name: tutorial1
on: push

jobs:
    job1:
        name: job1
        runs-on: ubuntu-latest
        steps:
        - name: step1
          run: echo "todays date"

    job2:
        name: job2
        runs-on: ubuntu-latest
        steps:
        - name: step2
          run: echo "todays date"

    job3:
        name: job3
        runs-on: ubuntu-latest
        steps:
        - name: step3
          run: echo "todays date"
          
    job4:
        name: job4
        runs-on: ubuntu-latest
        steps:
        - name: step4
          run: echo "I am job4"
